#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
recalibrate_mc_params.py — Recalibrate per-district Monte Carlo parameters
==========================================================================

PURPOSE
-------
Fits per-district baseMu and sigma for the Monte Carlo model used in
tracker.html (and indirectly in index.html's recommender). The model is:

    ln(votes) ~ Normal(baseMu + slope * ln(cost/budget), sigma)

where slope is fixed at 0.7 for all districts. Only baseMu (intercept) and
sigma (spread) are fitted per district, separately for BO and ZBO.

INPUT
-----
    bo-results/bo-results.json
        Combined historical voting data for all years (2022-2026+).
        Structure: { "2022": { "year":..., "districts": { "Aniołki": {
            "budget_bo":..., "budget_zbo":...,
            "projects_bo": [{"title":..., "cost":..., "votes":..., "won":...}],
            "projects_zbo": [...]
        }, ... }}, ... }

        Regenerated by:  parse_bo_results.py  (reads PDFs in bo-results/)

OUTPUT
------
Prints the full DISTRICT_MC_PARAMS JavaScript object, ready to paste into
tracker.html, replacing the existing block (lines ~409-445).

Also prints a summary table of all districts with n, baseMu, sigma for both
BO and ZBO, sorted by baseMu descending, for human review.

DISTRICT NAME MAPPING
---------------------
bo-results.json uses district names from historical PDFs. tracker.html uses
"normalized" names matching budgets.json. There are 4 known mismatches:

    PDF name (bo-results.json)          →  Normalized (tracker.html / budgets.json)
    ──────────────────────────────────     ──────────────────────────────────────────
    "Śródmieście"     (ó = U+00F3)     →  "Środmieście"      (o = plain o)
    "Orunia Górna-Gdańsk Południe"      →  "Orunia Górna - Gdańsk Południe"  (spaces around dash)
    "Zaspa Młyniec"                     →  "Zaspa-Młyniec"    (space → hyphen)
    "Zaspa Rozstaje"                    →  "Zaspa-Rozstaje"   (space → hyphen)

The script applies these mappings automatically.

ZBO THRESHOLD
-------------
Districts with fewer than MIN_ZBO_N ZBO data points get zbo: null, meaning
tracker.html will fall back to the global ZBO params (baseMu=5.8, sigma=0.8).
Currently MIN_ZBO_N = 8.

HOW TO RUN
----------
    # On Windows (from project root):
    powershell.exe -Command "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8; python -X utf8 recalibrate_mc_params.py"

    # On Linux / macOS:
    python3 recalibrate_mc_params.py

WHAT TO DO AFTER RUNNING
-------------------------
1. Review the summary table. Check for anomalies:
   - Any district with sigma > 1.5 may have data issues (bad budget, outlier).
   - Any district with n < 10 for BO is worth noting — low confidence.
   - Compare with previous values to see what changed and why.

2. Copy the generated JavaScript block from the "OUTPUT FOR tracker.html" section.

3. Open tracker.html and replace the DISTRICT_MC_PARAMS object (between the
   opening { on the "const DISTRICT_MC_PARAMS = {" line and the closing };)
   with the new output.

4. Also consider updating the global MC_PARAMS_BO / MC_PARAMS_ZBO if the
   overall median has shifted significantly. The global params are a few
   lines above DISTRICT_MC_PARAMS:
       const MC_PARAMS_BO  = { baseMu: 6.4, slope: 0.7, sigma: 0.8 };
       const MC_PARAMS_ZBO = { baseMu: 5.8, slope: 0.7, sigma: 0.8 };
   The script prints global (all-districts) stats for comparison.

5. Test tracker.html in a browser — expand a few projects and verify the
   dual MC curves look reasonable.

6. Commit the changes.

WHEN TO RE-RUN
--------------
- After regenerating bo-results.json (e.g., new year's results parsed, or
  parser bug fix like the Wrzeszcz Górny 2022 budget fix).
- After adding a new year of voting data (bo-results/bo-YYYY.pdf + re-parse).
- Annually before the new BO cycle starts.
"""

import json
import math
import sys
from collections import defaultdict

# ── Configuration ────────────────────────────────────────────────────────────

SLOPE = 0.7           # Fixed slope for ln(cost/budget) in the MC model
MIN_ZBO_N = 8         # Minimum ZBO records to include per-district ZBO params
BO_RESULTS = "bo-results/bo-results.json"

# District name mapping: bo-results.json name → tracker.html normalized name
# (matching budgets.json keys)
DISTRICT_NAME_MAP = {
    "\u015ar\u00f3dmie\u015bcie": "\u015arodmie\u015bcie",                          # Śródmieście → Środmieście (ó→o)
    "Orunia G\u00f3rna-Gda\u0144sk Po\u0142udnie": "Orunia G\u00f3rna - Gda\u0144sk Po\u0142udnie",  # add spaces around dash
    "Zaspa M\u0142yniec": "Zaspa-M\u0142yniec",                            # space → hyphen
    "Zaspa Rozstaje": "Zaspa-Rozstaje",                          # space → hyphen
}

# JS \u escape mapping for district names containing non-ASCII.
# Used to generate valid JS string keys inside <script> tags.
JS_ESCAPES = {
    "\u0104": "\\u0104",  # Ą
    "\u0105": "\\u0105",  # ą
    "\u0106": "\\u0106",  # Ć
    "\u0107": "\\u0107",  # ć
    "\u0118": "\\u0118",  # Ę
    "\u0119": "\\u0119",  # ę
    "\u0141": "\\u0141",  # Ł
    "\u0142": "\\u0142",  # ł
    "\u0143": "\\u0143",  # Ń
    "\u0144": "\\u0144",  # ń
    "\u00d3": "\\u00d3",  # Ó
    "\u00f3": "\\u00f3",  # ó
    "\u015a": "\\u015a",  # Ś
    "\u015b": "\\u015b",  # ś
    "\u0179": "\\u0179",  # Ź
    "\u017a": "\\u017a",  # ź
    "\u017b": "\\u017b",  # Ż
    "\u017c": "\\u017c",  # ż
}


def js_escape(s: str) -> str:
    """Escape Polish characters for use in JS string literals inside <script>."""
    return "".join(JS_ESCAPES.get(c, c) for c in s)


def norm_district(name: str) -> str:
    """Normalize a bo-results district name to the tracker.html key format."""
    return DISTRICT_NAME_MAP.get(name, name)


# ── Load data ────────────────────────────────────────────────────────────────

try:
    with open(BO_RESULTS, encoding="utf-8") as f:
        data = json.load(f)
except FileNotFoundError:
    print(f"ERROR: {BO_RESULTS} not found. Run parse_bo_results.py first.", file=sys.stderr)
    sys.exit(1)

# ── Collect all records ──────────────────────────────────────────────────────

# records_by_district[normalized_name]["bo"|"zbo"] = list of residuals
records_by_district = defaultdict(lambda: {"bo": [], "zbo": []})
all_bo_residuals = []
all_zbo_residuals = []
total_bo = 0
total_zbo = 0
skipped = 0

for year_str, year_data in data.items():
    if not isinstance(year_data, dict) or "districts" not in year_data:
        continue
    for dist_name, dist_data in year_data["districts"].items():
        norm_name = norm_district(dist_name)
        budget_bo = dist_data.get("budget_bo", 0)
        budget_zbo = dist_data.get("budget_zbo", 0)

        for ptype_key, budget, cat in [
            ("projects_bo", budget_bo, "bo"),
            ("projects_zbo", budget_zbo, "zbo"),
        ]:
            for p in dist_data.get(ptype_key, []):
                cost = p.get("cost", 0)
                votes = p.get("votes", 0)
                if cat == "bo":
                    total_bo += 1
                else:
                    total_zbo += 1
                if votes <= 0 or cost <= 0 or budget <= 0:
                    skipped += 1
                    continue
                resid = math.log(votes) - SLOPE * math.log(cost / budget)
                records_by_district[norm_name][cat].append(resid)
                if cat == "bo":
                    all_bo_residuals.append(resid)
                else:
                    all_zbo_residuals.append(resid)


def fit(residuals: list[float]) -> tuple[float, float, int]:
    """Return (baseMu, sigma, n) from residuals."""
    n = len(residuals)
    if n == 0:
        return 0.0, 0.0, 0
    mean_r = sum(residuals) / n
    sigma = (sum((r - mean_r) ** 2 for r in residuals) / n) ** 0.5
    return mean_r, sigma, n


# ── Fit all districts ────────────────────────────────────────────────────────

results = {}  # norm_name → {bo: (baseMu, sigma, n), zbo: (baseMu, sigma, n)|None}
for norm_name in sorted(records_by_district.keys()):
    bo_fit = fit(records_by_district[norm_name]["bo"])
    zbo_resids = records_by_district[norm_name]["zbo"]
    zbo_fit = fit(zbo_resids) if len(zbo_resids) >= MIN_ZBO_N else None
    results[norm_name] = {"bo": bo_fit, "zbo": zbo_fit}

# Global stats
global_bo = fit(all_bo_residuals)
global_zbo = fit(all_zbo_residuals)

# ── Print summary ────────────────────────────────────────────────────────────

print("=" * 100)
print("MONTE CARLO PARAMETER CALIBRATION RESULTS")
print(f"  Data source: {BO_RESULTS}")
print(f"  Years: {', '.join(sorted(y for y in data if isinstance(data[y], dict) and 'districts' in data[y]))}")
print(f"  Total records: {total_bo} BO + {total_zbo} ZBO = {total_bo + total_zbo}")
print(f"  Skipped (zero votes/cost/budget): {skipped}")
print(f"  Slope (fixed): {SLOPE}")
print(f"  Min ZBO N: {MIN_ZBO_N}")
print("=" * 100)

print(f"\nGLOBAL (all districts combined):")
print(f"  BO:  baseMu={global_bo[0]:.3f}  sigma={global_bo[1]:.3f}  n={global_bo[2]}")
print(f"  ZBO: baseMu={global_zbo[0]:.3f}  sigma={global_zbo[1]:.3f}  n={global_zbo[2]}")
print(f"  (Current tracker globals: BO baseMu=6.4 sigma=0.8, ZBO baseMu=5.8 sigma=0.8)")

print(f"\nPER-DISTRICT SUMMARY (sorted by BO baseMu descending):")
print(f"{'District':<42} {'BO baseMu':>10} {'BO sig':>7} {'BO n':>5}   {'ZBO baseMu':>11} {'ZBO sig':>8} {'ZBO n':>6}")
print("-" * 100)

sorted_districts = sorted(results.keys(), key=lambda d: results[d]["bo"][0], reverse=True)
for d in sorted_districts:
    bo = results[d]["bo"]
    zbo = results[d]["zbo"]
    zbo_str = f"  {zbo[0]:11.3f} {zbo[1]:8.3f} {zbo[2]:6d}" if zbo else "        null                "
    flag = ""
    if bo[1] > 1.3:
        flag += " ⚠ high sigma"
    if bo[2] < 10:
        flag += " ⚠ low n"
    print(f"{d:<42} {bo[0]:10.3f} {bo[1]:7.3f} {bo[2]:5d}{zbo_str}{flag}")

# ── Generate JS output ──────────────────────────────────────────────────────

print("\n" + "=" * 100)
print("OUTPUT FOR tracker.html — replace the DISTRICT_MC_PARAMS block:")
print("=" * 100)
print()

# Find max key length for alignment
max_key_len = max(len(f'"{js_escape(d)}"') for d in results)

# JS output is alphabetical (matching tracker.html convention)
import locale
try:
    locale.setlocale(locale.LC_COLLATE, "pl_PL.UTF-8")
    alpha_districts = sorted(results.keys(), key=locale.strxfrm)
except locale.Error:
    # Fallback: plain sort (puts Ś, Ż at end which is correct for Polish)
    alpha_districts = sorted(results.keys())

lines = []
for d in alpha_districts:
    bo = results[d]["bo"]
    zbo = results[d]["zbo"]
    js_key = f'"{js_escape(d)}"'
    padded_key = js_key.ljust(max_key_len)

    bo_str = f"bo: {{baseMu:{bo[0]:.3f}, sigma:{bo[1]:.3f}}}"

    if zbo:
        zbo_str = f"zbo: {{baseMu:{zbo[0]:.3f}, sigma:{zbo[1]:.3f}}}"
    else:
        n_zbo = len(records_by_district[d]["zbo"])
        zbo_str = "zbo: null"
        zbo_str += f" }},         // zbo n={n_zbo}"

    if zbo:
        line = f"  {padded_key}: {{ {bo_str}, {zbo_str} }},"
    else:
        # zbo: null already includes the closing }}, and comment
        line = f"  {padded_key}: {{ {bo_str}, {zbo_str}"

    lines.append(line)

print("const DISTRICT_MC_PARAMS = {")
for line in lines:
    print(line)
print("};")

# ── Diff vs current values ──────────────────────────────────────────────────
# This section is informational — shows what changed compared to current
# tracker.html values, if they can be parsed.

print("\n" + "=" * 100)
print("DONE. Review the summary table above, then paste the JS block into tracker.html.")
print("See the script header for detailed instructions.")
print("=" * 100)
